# Form implementation generated from reading ui file '.\ui_files\CalculateTimeWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CalculateTime(object):
    def setupUi(self, CalculateTime):
        CalculateTime.setObjectName("CalculateTime")
        CalculateTime.resize(253, 136)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalculateTime.sizePolicy().hasHeightForWidth())
        CalculateTime.setSizePolicy(sizePolicy)
        CalculateTime.setMaximumSize(QtCore.QSize(16777215, 136))
        font = QtGui.QFont()
        font.setPointSize(12)
        CalculateTime.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(CalculateTime)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(CalculateTime)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.cb_rate_time = QtWidgets.QComboBox(CalculateTime)
        self.cb_rate_time.setObjectName("cb_rate_time")
        self.cb_rate_time.addItem("")
        self.cb_rate_time.addItem("")
        self.cb_rate_time.addItem("")
        self.gridLayout.addWidget(self.cb_rate_time, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(CalculateTime)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.dsb_rate = QtWidgets.QDoubleSpinBox(CalculateTime)
        self.dsb_rate.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsb_rate.setAccelerated(True)
        self.dsb_rate.setProperty("showGroupSeparator", True)
        self.dsb_rate.setDecimals(0)
        self.dsb_rate.setMaximum(1000000000.0)
        self.dsb_rate.setObjectName("dsb_rate")
        self.gridLayout.addWidget(self.dsb_rate, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(CalculateTime)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.dsb_needed = QtWidgets.QDoubleSpinBox(CalculateTime)
        self.dsb_needed.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsb_needed.setAccelerated(True)
        self.dsb_needed.setProperty("showGroupSeparator", True)
        self.dsb_needed.setDecimals(0)
        self.dsb_needed.setMaximum(1000000000.0)
        self.dsb_needed.setObjectName("dsb_needed")
        self.gridLayout.addWidget(self.dsb_needed, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(CalculateTime)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineedit_result = QtWidgets.QLineEdit(CalculateTime)
        self.lineedit_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineedit_result.setReadOnly(True)
        self.lineedit_result.setObjectName("lineedit_result")
        self.gridLayout.addWidget(self.lineedit_result, 3, 1, 1, 1)

        self.retranslateUi(CalculateTime)
        QtCore.QMetaObject.connectSlotsByName(CalculateTime)

    def retranslateUi(self, CalculateTime):
        _translate = QtCore.QCoreApplication.translate
        CalculateTime.setWindowTitle(_translate("CalculateTime", "Calculate Time"))
        self.label_4.setText(_translate("CalculateTime", "Rate of time"))
        self.cb_rate_time.setItemText(0, _translate("CalculateTime", "Hour"))
        self.cb_rate_time.setItemText(1, _translate("CalculateTime", "Minute"))
        self.cb_rate_time.setItemText(2, _translate("CalculateTime", "Second"))
        self.label.setText(_translate("CalculateTime", "Rate"))
        self.label_2.setText(_translate("CalculateTime", "Needed"))
        self.label_3.setText(_translate("CalculateTime", "Total Time"))
